//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Battlesnake.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameState {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameState() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Battlesnake.Test.GameState", typeof(GameState).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:{&quot;id&quot;:&quot;e15136fd-6b08-4d43-8373-9188365d9be3&quot;,&quot;ruleset&quot;:{&quot;name&quot;:&quot;standard&quot;,&quot;version&quot;:&quot;?&quot;,&quot;settings&quot;:{&quot;foodSpawnChance&quot;:15,&quot;minimumFood&quot;:1,&quot;royale&quot;:{},&quot;squad&quot;:{&quot;allowBodyCollisions&quot;:false,&quot;sharedElimination&quot;:false,&quot;sharedHealth&quot;:false,&quot;sharedLength&quot;:false}}},&quot;timeout&quot;:500,&quot;source&quot;:&quot;arena&quot;},&quot;turn&quot;:43,&quot;board&quot;:{&quot;width&quot;:11,&quot;height&quot;:11,&quot;food&quot;:[{&quot;x&quot;:9,&quot;y&quot;:5},{&quot;x&quot;:1,&quot;y&quot;:0},{&quot;x&quot;:2,&quot;y&quot;:6}],&quot;hazards&quot;:[],&quot;snakes&quot;:[{&quot;id&quot;:&quot;gs_88mxm64vprBjGjkTFfvRdCyb&quot;,&quot;name&quot;:&quot;BwukMaxi&quot;,&quot;body&quot;:[{&quot;x&quot;:1,&quot;y&quot;:8},{&quot;x&quot;:1,&quot;y&quot;:7},{&quot;x&quot;:1,&quot;y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MoveUpAgainstLeftWallForHeadToHead {
            get {
                return ResourceManager.GetString("MoveUpAgainstLeftWallForHeadToHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:{&quot;id&quot;:&quot;eb0e1f28-6585-4661-97d3-b1b2dc24f308&quot;,&quot;ruleset&quot;:{&quot;name&quot;:&quot;standard&quot;,&quot;version&quot;:&quot;?&quot;,&quot;settings&quot;:{&quot;foodSpawnChance&quot;:15,&quot;minimumFood&quot;:1,&quot;royale&quot;:{},&quot;squad&quot;:{&quot;allowBodyCollisions&quot;:false,&quot;sharedElimination&quot;:false,&quot;sharedHealth&quot;:false,&quot;sharedLength&quot;:false}}},&quot;timeout&quot;:500,&quot;source&quot;:&quot;arena&quot;},&quot;turn&quot;:24,&quot;board&quot;:{&quot;width&quot;:11,&quot;height&quot;:11,&quot;food&quot;:[{&quot;x&quot;:7,&quot;y&quot;:2}],&quot;hazards&quot;:[],&quot;snakes&quot;:[{&quot;id&quot;:&quot;gs_HGkRHxPqFCxVj6vpmSKGGphK&quot;,&quot;name&quot;:&quot;mudbuzzer&quot;,&quot;body&quot;:[{&quot;x&quot;:4,&quot;y&quot;:2},{&quot;x&quot;:4,&quot;y&quot;:3},{&quot;x&quot;:3,&quot;y&quot;:3},{&quot;x&quot;:3,&quot;y&quot;:2},{&quot;x&quot;:3,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoHeadToHead {
            get {
                return ResourceManager.GetString("NoHeadToHead", resourceCulture);
            }
        }
    }
}
