//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Battlesnake.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameStateDuel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameStateDuel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Battlesnake.Test.GameStateDuel", typeof(GameStateDuel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:{&quot;id&quot;:&quot;2451ce27-ecb9-448b-934d-e7a96fe18473&quot;,&quot;ruleset&quot;:{&quot;name&quot;:&quot;standard&quot;,&quot;version&quot;:&quot;?&quot;,&quot;settings&quot;:{&quot;foodSpawnChance&quot;:15,&quot;minimumFood&quot;:1,&quot;royale&quot;:{},&quot;squad&quot;:{&quot;allowBodyCollisions&quot;:false,&quot;sharedElimination&quot;:false,&quot;sharedHealth&quot;:false,&quot;sharedLength&quot;:false}}},&quot;timeout&quot;:500,&quot;source&quot;:&quot;arena&quot;},&quot;turn&quot;:136,&quot;board&quot;:{&quot;width&quot;:11,&quot;height&quot;:11,&quot;food&quot;:[{&quot;x&quot;:6,&quot;y&quot;:10},{&quot;x&quot;:10,&quot;y&quot;:6},{&quot;x&quot;:1,&quot;y&quot;:1}],&quot;hazards&quot;:[],&quot;snakes&quot;:[{&quot;id&quot;:&quot;gs_Pbc8dTFKMv9yt4Jb3td4jvwG&quot;,&quot;name&quot;:&quot;BwukMaxi&quot;,&quot;body&quot;:[{&quot;x&quot;:8,&quot;y&quot;:4},{&quot;x&quot;:9,&quot;y&quot;:4},{&quot;x&quot;:9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttemptPossibleCornorTrapLongOpponentPart1 {
            get {
                return ResourceManager.GetString("AttemptPossibleCornorTrapLongOpponentPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:{&quot;id&quot;:&quot;386747&quot;,&quot;ruleset&quot;:{&quot;name&quot;:&quot;standard&quot;,&quot;version&quot;:&quot;v.1.2.3&quot;},&quot;timeout&quot;:500},&quot;turn&quot;:200,&quot;you&quot;:{&quot;health&quot;:47,&quot;id&quot;:&quot;you&quot;,&quot;name&quot;:&quot;#22aa34&quot;,&quot;body&quot;:[{&quot;x&quot;:8,&quot;y&quot;:5},{&quot;x&quot;:8,&quot;y&quot;:4},{&quot;x&quot;:9,&quot;y&quot;:4},{&quot;x&quot;:9,&quot;y&quot;:3},{&quot;x&quot;:8,&quot;y&quot;:3}],&quot;head&quot;:{&quot;x&quot;:8,&quot;y&quot;:5},&quot;length&quot;:5},&quot;board&quot;:{&quot;food&quot;:[{&quot;x&quot;:6,&quot;y&quot;:10},{&quot;x&quot;:10,&quot;y&quot;:6},{&quot;x&quot;:1,&quot;y&quot;:1}],&quot;height&quot;:11,&quot;width&quot;:11,&quot;snakes&quot;:[{&quot;health&quot;:47,&quot;id&quot;:&quot;you&quot;,&quot;name&quot;:&quot;#22aa34&quot;,&quot;body&quot;:[{&quot;x&quot;:8,&quot;y&quot;:5},{&quot;x&quot;:8,&quot;y&quot;:4},{&quot;x&quot;:9,&quot;y&quot;:4},{&quot;x&quot;:9,&quot;y&quot;:3},{&q....
        /// </summary>
        internal static string AttemptPossibleCornorTrapLongOpponentPart2 {
            get {
                return ResourceManager.GetString("AttemptPossibleCornorTrapLongOpponentPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:{&quot;id&quot;:&quot;0e455601-a8f9-4c50-8da2-2e09a296b827&quot;,&quot;ruleset&quot;:{&quot;name&quot;:&quot;standard&quot;,&quot;version&quot;:&quot;?&quot;,&quot;settings&quot;:{&quot;foodSpawnChance&quot;:15,&quot;minimumFood&quot;:1,&quot;royale&quot;:{},&quot;squad&quot;:{&quot;allowBodyCollisions&quot;:false,&quot;sharedElimination&quot;:false,&quot;sharedHealth&quot;:false,&quot;sharedLength&quot;:false}}},&quot;timeout&quot;:500,&quot;source&quot;:&quot;arena&quot;},&quot;turn&quot;:3,&quot;board&quot;:{&quot;width&quot;:11,&quot;height&quot;:11,&quot;food&quot;:[{&quot;x&quot;:10,&quot;y&quot;:4},{&quot;x&quot;:4,&quot;y&quot;:0},{&quot;x&quot;:5,&quot;y&quot;:5}],&quot;hazards&quot;:[],&quot;snakes&quot;:[{&quot;id&quot;:&quot;gs_fXPyPw77vrVgSWMdtXmcq4JT&quot;,&quot;name&quot;:&quot;Epitaph&quot;,&quot;body&quot;:[{&quot;x&quot;:6,&quot;y&quot;:5},{&quot;x&quot;:7,&quot;y&quot;:5},{&quot;x&quot;:8,&quot;y&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AvoidHeadToHeadCenterFood {
            get {
                return ResourceManager.GetString("AvoidHeadToHeadCenterFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:{&quot;id&quot;:&quot;7a27630d-f962-4c15-aed9-f90f8b6a40e1&quot;,&quot;ruleset&quot;:{&quot;name&quot;:&quot;standard&quot;,&quot;version&quot;:&quot;?&quot;,&quot;settings&quot;:{&quot;foodSpawnChance&quot;:15,&quot;minimumFood&quot;:1,&quot;royale&quot;:{},&quot;squad&quot;:{&quot;allowBodyCollisions&quot;:false,&quot;sharedElimination&quot;:false,&quot;sharedHealth&quot;:false,&quot;sharedLength&quot;:false}}},&quot;timeout&quot;:500,&quot;source&quot;:&quot;arena&quot;},&quot;turn&quot;:242,&quot;board&quot;:{&quot;width&quot;:11,&quot;height&quot;:11,&quot;food&quot;:[{&quot;x&quot;:0,&quot;y&quot;:9},{&quot;x&quot;:2,&quot;y&quot;:8},{&quot;x&quot;:0,&quot;y&quot;:3}],&quot;hazards&quot;:[],&quot;snakes&quot;:[{&quot;id&quot;:&quot;gs_ywJkWdXjWPjQthD8DrXrfwq6&quot;,&quot;name&quot;:&quot;BwukMaxi&quot;,&quot;body&quot;:[{&quot;x&quot;:0,&quot;y&quot;:2},{&quot;x&quot;:1,&quot;y&quot;:2},{&quot;x&quot;:1,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DontEnterSmallCaves {
            get {
                return ResourceManager.GetString("DontEnterSmallCaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:{&quot;id&quot;:&quot;5bd77fe8-f544-4c15-999f-cc40f8980395&quot;,&quot;ruleset&quot;:{&quot;name&quot;:&quot;standard&quot;,&quot;version&quot;:&quot;?&quot;,&quot;settings&quot;:{&quot;foodSpawnChance&quot;:15,&quot;minimumFood&quot;:1,&quot;royale&quot;:{},&quot;squad&quot;:{&quot;allowBodyCollisions&quot;:false,&quot;sharedElimination&quot;:false,&quot;sharedHealth&quot;:false,&quot;sharedLength&quot;:false}}},&quot;timeout&quot;:500,&quot;source&quot;:&quot;arena&quot;},&quot;turn&quot;:254,&quot;board&quot;:{&quot;width&quot;:11,&quot;height&quot;:11,&quot;food&quot;:[{&quot;x&quot;:10,&quot;y&quot;:10},{&quot;x&quot;:0,&quot;y&quot;:8},{&quot;x&quot;:5,&quot;y&quot;:10},{&quot;x&quot;:1,&quot;y&quot;:10},{&quot;x&quot;:4,&quot;y&quot;:7},{&quot;x&quot;:0,&quot;y&quot;:10},{&quot;x&quot;:3,&quot;y&quot;:1}],&quot;hazards&quot;:[],&quot;snakes&quot;:[{&quot;id&quot;:&quot;gs_YgS7TJGcrdwpQcxGGpr9PdSd&quot;,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DrawIsBetterThanCertainDeath {
            get {
                return ResourceManager.GetString("DrawIsBetterThanCertainDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:{&quot;id&quot;:&quot;651725&quot;,&quot;ruleset&quot;:{&quot;name&quot;:&quot;standard&quot;,&quot;version&quot;:&quot;v.1.2.3&quot;},&quot;timeout&quot;:500},&quot;turn&quot;:200,&quot;you&quot;:{&quot;health&quot;:1,&quot;id&quot;:&quot;you&quot;,&quot;name&quot;:&quot;#22aa34&quot;,&quot;body&quot;:[{&quot;x&quot;:4,&quot;y&quot;:6},{&quot;x&quot;:5,&quot;y&quot;:6},{&quot;x&quot;:6,&quot;y&quot;:6}],&quot;head&quot;:{&quot;x&quot;:4,&quot;y&quot;:6},&quot;length&quot;:3},&quot;board&quot;:{&quot;food&quot;:[{&quot;x&quot;:4,&quot;y&quot;:5}],&quot;height&quot;:11,&quot;width&quot;:11,&quot;snakes&quot;:[{&quot;health&quot;:1,&quot;id&quot;:&quot;you&quot;,&quot;name&quot;:&quot;#22aa34&quot;,&quot;body&quot;:[{&quot;x&quot;:4,&quot;y&quot;:6},{&quot;x&quot;:5,&quot;y&quot;:6},{&quot;x&quot;:6,&quot;y&quot;:6}],&quot;head&quot;:{&quot;x&quot;:4,&quot;y&quot;:6},&quot;length&quot;:3},{&quot;health&quot;:100,&quot;id&quot;:&quot;#FF5b39&quot;,&quot;name&quot;:&quot;#FF5b39&quot;,&quot;b....
        /// </summary>
        internal static string EatYoureHungryOneHpLeft {
            get {
                return ResourceManager.GetString("EatYoureHungryOneHpLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:{&quot;id&quot;:&quot;e15136fd-6b08-4d43-8373-9188365d9be3&quot;,&quot;ruleset&quot;:{&quot;name&quot;:&quot;standard&quot;,&quot;version&quot;:&quot;?&quot;,&quot;settings&quot;:{&quot;foodSpawnChance&quot;:15,&quot;minimumFood&quot;:1,&quot;royale&quot;:{},&quot;squad&quot;:{&quot;allowBodyCollisions&quot;:false,&quot;sharedElimination&quot;:false,&quot;sharedHealth&quot;:false,&quot;sharedLength&quot;:false}}},&quot;timeout&quot;:500,&quot;source&quot;:&quot;arena&quot;},&quot;turn&quot;:43,&quot;board&quot;:{&quot;width&quot;:11,&quot;height&quot;:11,&quot;food&quot;:[{&quot;x&quot;:9,&quot;y&quot;:5},{&quot;x&quot;:1,&quot;y&quot;:0},{&quot;x&quot;:2,&quot;y&quot;:6}],&quot;hazards&quot;:[],&quot;snakes&quot;:[{&quot;id&quot;:&quot;gs_88mxm64vprBjGjkTFfvRdCyb&quot;,&quot;name&quot;:&quot;BwukMaxi&quot;,&quot;body&quot;:[{&quot;x&quot;:1,&quot;y&quot;:8},{&quot;x&quot;:1,&quot;y&quot;:7},{&quot;x&quot;:1,&quot;y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MoveUpAgainstLeftWallForHeadToHead {
            get {
                return ResourceManager.GetString("MoveUpAgainstLeftWallForHeadToHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:{&quot;id&quot;:&quot;720962&quot;,&quot;ruleset&quot;:{&quot;name&quot;:&quot;standard&quot;,&quot;version&quot;:&quot;v.1.2.3&quot;},&quot;timeout&quot;:500},&quot;turn&quot;:200,&quot;you&quot;:{&quot;health&quot;:100,&quot;id&quot;:&quot;you&quot;,&quot;name&quot;:&quot;#22aa34&quot;,&quot;body&quot;:[{&quot;x&quot;:0,&quot;y&quot;:10},{&quot;x&quot;:0,&quot;y&quot;:9},{&quot;x&quot;:0,&quot;y&quot;:8},{&quot;x&quot;:0,&quot;y&quot;:7}],&quot;head&quot;:{&quot;x&quot;:0,&quot;y&quot;:10},&quot;length&quot;:4},&quot;board&quot;:{&quot;food&quot;:[{&quot;x&quot;:6,&quot;y&quot;:6}],&quot;height&quot;:11,&quot;width&quot;:11,&quot;snakes&quot;:[{&quot;health&quot;:100,&quot;id&quot;:&quot;you&quot;,&quot;name&quot;:&quot;#22aa34&quot;,&quot;body&quot;:[{&quot;x&quot;:0,&quot;y&quot;:10},{&quot;x&quot;:0,&quot;y&quot;:9},{&quot;x&quot;:0,&quot;y&quot;:8},{&quot;x&quot;:0,&quot;y&quot;:7}],&quot;head&quot;:{&quot;x&quot;:0,&quot;y&quot;:10},&quot;length&quot;:4},{&quot;health&quot;:100,&qu....
        /// </summary>
        internal static string NeverRunIntoWalls {
            get {
                return ResourceManager.GetString("NeverRunIntoWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:{&quot;id&quot;:&quot;720962&quot;,&quot;ruleset&quot;:{&quot;name&quot;:&quot;standard&quot;,&quot;version&quot;:&quot;v.1.2.3&quot;},&quot;timeout&quot;:500},&quot;turn&quot;:200,&quot;you&quot;:{&quot;health&quot;:100,&quot;id&quot;:&quot;you&quot;,&quot;name&quot;:&quot;#22aa34&quot;,&quot;body&quot;:[{&quot;x&quot;:3,&quot;y&quot;:6},{&quot;x&quot;:3,&quot;y&quot;:7},{&quot;x&quot;:4,&quot;y&quot;:7},{&quot;x&quot;:4,&quot;y&quot;:6},{&quot;x&quot;:4,&quot;y&quot;:5},{&quot;x&quot;:3,&quot;y&quot;:5},{&quot;x&quot;:2,&quot;y&quot;:5}],&quot;head&quot;:{&quot;x&quot;:3,&quot;y&quot;:6},&quot;length&quot;:7},&quot;board&quot;:{&quot;food&quot;:[{&quot;x&quot;:6,&quot;y&quot;:6}],&quot;height&quot;:11,&quot;width&quot;:11,&quot;snakes&quot;:[{&quot;health&quot;:100,&quot;id&quot;:&quot;you&quot;,&quot;name&quot;:&quot;#22aa34&quot;,&quot;body&quot;:[{&quot;x&quot;:3,&quot;y&quot;:6},{&quot;x&quot;:3,&quot;y&quot;:7},{&quot;x&quot;:4,&quot;y&quot;:7},{&quot;x&quot;:4,&quot;y&quot;:6},{&q....
        /// </summary>
        internal static string NeverRunIntoYourSelf {
            get {
                return ResourceManager.GetString("NeverRunIntoYourSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:{&quot;id&quot;:&quot;eb0e1f28-6585-4661-97d3-b1b2dc24f308&quot;,&quot;ruleset&quot;:{&quot;name&quot;:&quot;standard&quot;,&quot;version&quot;:&quot;?&quot;,&quot;settings&quot;:{&quot;foodSpawnChance&quot;:15,&quot;minimumFood&quot;:1,&quot;royale&quot;:{},&quot;squad&quot;:{&quot;allowBodyCollisions&quot;:false,&quot;sharedElimination&quot;:false,&quot;sharedHealth&quot;:false,&quot;sharedLength&quot;:false}}},&quot;timeout&quot;:500,&quot;source&quot;:&quot;arena&quot;},&quot;turn&quot;:24,&quot;board&quot;:{&quot;width&quot;:11,&quot;height&quot;:11,&quot;food&quot;:[{&quot;x&quot;:7,&quot;y&quot;:2}],&quot;hazards&quot;:[],&quot;snakes&quot;:[{&quot;id&quot;:&quot;gs_HGkRHxPqFCxVj6vpmSKGGphK&quot;,&quot;name&quot;:&quot;mudbuzzer&quot;,&quot;body&quot;:[{&quot;x&quot;:4,&quot;y&quot;:2},{&quot;x&quot;:4,&quot;y&quot;:3},{&quot;x&quot;:3,&quot;y&quot;:3},{&quot;x&quot;:3,&quot;y&quot;:2},{&quot;x&quot;:3,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoHeadToHead {
            get {
                return ResourceManager.GetString("NoHeadToHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:{&quot;id&quot;:&quot;85912a8c-e62a-47ab-9231-67b438239d9c&quot;,&quot;ruleset&quot;:{&quot;name&quot;:&quot;standard&quot;,&quot;version&quot;:&quot;?&quot;,&quot;settings&quot;:{&quot;foodSpawnChance&quot;:15,&quot;minimumFood&quot;:1,&quot;royale&quot;:{},&quot;squad&quot;:{&quot;allowBodyCollisions&quot;:false,&quot;sharedElimination&quot;:false,&quot;sharedHealth&quot;:false,&quot;sharedLength&quot;:false}}},&quot;timeout&quot;:500,&quot;source&quot;:&quot;arena&quot;},&quot;turn&quot;:226,&quot;board&quot;:{&quot;width&quot;:11,&quot;height&quot;:11,&quot;food&quot;:[{&quot;x&quot;:0,&quot;y&quot;:5},{&quot;x&quot;:0,&quot;y&quot;:10},{&quot;x&quot;:1,&quot;y&quot;:7},{&quot;x&quot;:1,&quot;y&quot;:4},{&quot;x&quot;:0,&quot;y&quot;:4},{&quot;x&quot;:3,&quot;y&quot;:0},{&quot;x&quot;:6,&quot;y&quot;:3}],&quot;hazards&quot;:[],&quot;snakes&quot;:[{&quot;id&quot;:&quot;gs_Dt3wyB4qkGYv4Ycvx3mvfyP8&quot;,&quot;name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OnlyApplyEatMoveOnNextTurn {
            get {
                return ResourceManager.GetString("OnlyApplyEatMoveOnNextTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:{&quot;id&quot;:&quot;4356f7dd-1c30-4cfc-8220-990e587f2aac&quot;,&quot;ruleset&quot;:{&quot;name&quot;:&quot;standard&quot;,&quot;version&quot;:&quot;?&quot;,&quot;settings&quot;:{&quot;foodSpawnChance&quot;:15,&quot;minimumFood&quot;:1,&quot;royale&quot;:{},&quot;squad&quot;:{&quot;allowBodyCollisions&quot;:false,&quot;sharedElimination&quot;:false,&quot;sharedHealth&quot;:false,&quot;sharedLength&quot;:false}}},&quot;timeout&quot;:500,&quot;source&quot;:&quot;arena&quot;},&quot;turn&quot;:26,&quot;board&quot;:{&quot;width&quot;:11,&quot;height&quot;:11,&quot;food&quot;:[{&quot;x&quot;:6,&quot;y&quot;:0},{&quot;x&quot;:10,&quot;y&quot;:1},{&quot;x&quot;:5,&quot;y&quot;:5}],&quot;hazards&quot;:[],&quot;snakes&quot;:[{&quot;id&quot;:&quot;gs_TXPXH694F4xrYMkqwmwGGvfD&quot;,&quot;name&quot;:&quot;BwukMaxi&quot;,&quot;body&quot;:[{&quot;x&quot;:9,&quot;y&quot;:9},{&quot;x&quot;:9,&quot;y&quot;:8},{&quot;x&quot;:9,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PinUpAgainstWall {
            get {
                return ResourceManager.GetString("PinUpAgainstWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:{&quot;id&quot;:&quot;651725&quot;,&quot;ruleset&quot;:{&quot;name&quot;:&quot;standard&quot;,&quot;version&quot;:&quot;v.1.2.3&quot;},&quot;timeout&quot;:500},&quot;turn&quot;:200,&quot;you&quot;:{&quot;health&quot;:1,&quot;id&quot;:&quot;you&quot;,&quot;name&quot;:&quot;#22aa34&quot;,&quot;body&quot;:[{&quot;x&quot;:4,&quot;y&quot;:6},{&quot;x&quot;:5,&quot;y&quot;:6},{&quot;x&quot;:6,&quot;y&quot;:6}],&quot;head&quot;:{&quot;x&quot;:4,&quot;y&quot;:6},&quot;length&quot;:3},&quot;board&quot;:{&quot;food&quot;:[{&quot;x&quot;:4,&quot;y&quot;:5}],&quot;height&quot;:11,&quot;width&quot;:11,&quot;snakes&quot;:[{&quot;health&quot;:1,&quot;id&quot;:&quot;you&quot;,&quot;name&quot;:&quot;#22aa34&quot;,&quot;body&quot;:[{&quot;x&quot;:4,&quot;y&quot;:6},{&quot;x&quot;:5,&quot;y&quot;:6},{&quot;x&quot;:6,&quot;y&quot;:6}],&quot;head&quot;:{&quot;x&quot;:4,&quot;y&quot;:6},&quot;length&quot;:3},{&quot;health&quot;:100,&quot;id&quot;:&quot;#FF5b39&quot;,&quot;name&quot;:&quot;#FF5b39&quot;,&quot;b....
        /// </summary>
        internal static string PreferDrawWhenHungryEvenWithOneHpLeft {
            get {
                return ResourceManager.GetString("PreferDrawWhenHungryEvenWithOneHpLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:{&quot;id&quot;:&quot;045f087c-bfc6-4b63-aa6f-97e50c85de06&quot;,&quot;ruleset&quot;:{&quot;name&quot;:&quot;standard&quot;,&quot;version&quot;:&quot;?&quot;,&quot;settings&quot;:{&quot;foodSpawnChance&quot;:15,&quot;minimumFood&quot;:1,&quot;royale&quot;:{},&quot;squad&quot;:{&quot;allowBodyCollisions&quot;:false,&quot;sharedElimination&quot;:false,&quot;sharedHealth&quot;:false,&quot;sharedLength&quot;:false}}},&quot;timeout&quot;:500,&quot;source&quot;:&quot;arena&quot;},&quot;turn&quot;:194,&quot;board&quot;:{&quot;width&quot;:11,&quot;height&quot;:11,&quot;food&quot;:[{&quot;x&quot;:10,&quot;y&quot;:3},{&quot;x&quot;:1,&quot;y&quot;:0},{&quot;x&quot;:10,&quot;y&quot;:8},{&quot;x&quot;:0,&quot;y&quot;:1},{&quot;x&quot;:3,&quot;y&quot;:9},{&quot;x&quot;:9,&quot;y&quot;:4},{&quot;x&quot;:2,&quot;y&quot;:5},{&quot;x&quot;:0,&quot;y&quot;:0}],&quot;hazards&quot;:[],&quot;snakes&quot;:[{&quot;id&quot;:&quot;gs_WV6TfWbCD7VhkwY3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrapOpponentIntoCavePart1 {
            get {
                return ResourceManager.GetString("TrapOpponentIntoCavePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:{&quot;id&quot;:&quot;045f087c-bfc6-4b63-aa6f-97e50c85de06&quot;,&quot;ruleset&quot;:{&quot;name&quot;:&quot;standard&quot;,&quot;version&quot;:&quot;?&quot;,&quot;settings&quot;:{&quot;foodSpawnChance&quot;:15,&quot;minimumFood&quot;:1,&quot;royale&quot;:{},&quot;squad&quot;:{&quot;allowBodyCollisions&quot;:false,&quot;sharedElimination&quot;:false,&quot;sharedHealth&quot;:false,&quot;sharedLength&quot;:false}}},&quot;timeout&quot;:500,&quot;source&quot;:&quot;arena&quot;},&quot;turn&quot;:195,&quot;board&quot;:{&quot;width&quot;:11,&quot;height&quot;:11,&quot;food&quot;:[{&quot;x&quot;:10,&quot;y&quot;:3},{&quot;x&quot;:1,&quot;y&quot;:0},{&quot;x&quot;:10,&quot;y&quot;:8},{&quot;x&quot;:0,&quot;y&quot;:1},{&quot;x&quot;:3,&quot;y&quot;:9},{&quot;x&quot;:9,&quot;y&quot;:4},{&quot;x&quot;:2,&quot;y&quot;:5},{&quot;x&quot;:0,&quot;y&quot;:0}],&quot;hazards&quot;:[],&quot;snakes&quot;:[{&quot;id&quot;:&quot;gs_WV6TfWbCD7VhkwY3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrapOpponentIntoCavePart2 {
            get {
                return ResourceManager.GetString("TrapOpponentIntoCavePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:{&quot;id&quot;:&quot;045f087c-bfc6-4b63-aa6f-97e50c85de06&quot;,&quot;ruleset&quot;:{&quot;name&quot;:&quot;standard&quot;,&quot;version&quot;:&quot;?&quot;,&quot;settings&quot;:{&quot;foodSpawnChance&quot;:15,&quot;minimumFood&quot;:1,&quot;royale&quot;:{},&quot;squad&quot;:{&quot;allowBodyCollisions&quot;:false,&quot;sharedElimination&quot;:false,&quot;sharedHealth&quot;:false,&quot;sharedLength&quot;:false}}},&quot;timeout&quot;:500,&quot;source&quot;:&quot;arena&quot;},&quot;turn&quot;:196,&quot;board&quot;:{&quot;width&quot;:11,&quot;height&quot;:11,&quot;food&quot;:[{&quot;x&quot;:10,&quot;y&quot;:3},{&quot;x&quot;:1,&quot;y&quot;:0},{&quot;x&quot;:10,&quot;y&quot;:8},{&quot;x&quot;:0,&quot;y&quot;:1},{&quot;x&quot;:3,&quot;y&quot;:9},{&quot;x&quot;:9,&quot;y&quot;:4},{&quot;x&quot;:2,&quot;y&quot;:5},{&quot;x&quot;:0,&quot;y&quot;:0}],&quot;hazards&quot;:[],&quot;snakes&quot;:[{&quot;id&quot;:&quot;gs_WV6TfWbCD7VhkwY3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrapOpponentIntoCavePart3 {
            get {
                return ResourceManager.GetString("TrapOpponentIntoCavePart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;game&quot;:{&quot;id&quot;:&quot;045f087c-bfc6-4b63-aa6f-97e50c85de06&quot;,&quot;ruleset&quot;:{&quot;name&quot;:&quot;standard&quot;,&quot;version&quot;:&quot;?&quot;,&quot;settings&quot;:{&quot;foodSpawnChance&quot;:15,&quot;minimumFood&quot;:1,&quot;royale&quot;:{},&quot;squad&quot;:{&quot;allowBodyCollisions&quot;:false,&quot;sharedElimination&quot;:false,&quot;sharedHealth&quot;:false,&quot;sharedLength&quot;:false}}},&quot;timeout&quot;:500,&quot;source&quot;:&quot;arena&quot;},&quot;turn&quot;:197,&quot;board&quot;:{&quot;width&quot;:11,&quot;height&quot;:11,&quot;food&quot;:[{&quot;x&quot;:10,&quot;y&quot;:3},{&quot;x&quot;:1,&quot;y&quot;:0},{&quot;x&quot;:10,&quot;y&quot;:8},{&quot;x&quot;:0,&quot;y&quot;:1},{&quot;x&quot;:3,&quot;y&quot;:9},{&quot;x&quot;:9,&quot;y&quot;:4},{&quot;x&quot;:2,&quot;y&quot;:5},{&quot;x&quot;:0,&quot;y&quot;:0}],&quot;hazards&quot;:[],&quot;snakes&quot;:[{&quot;id&quot;:&quot;gs_WV6TfWbCD7VhkwY3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrapOpponentIntoCavePart4 {
            get {
                return ResourceManager.GetString("TrapOpponentIntoCavePart4", resourceCulture);
            }
        }
    }
}
